
"""

성별 이름
남     개똥
남      바보
남     나무
여     티비
여     고양이
남     개똥


성별 사람수
남     3
여     2


SELECT 성별, COUNT(DISTINCT 이름) AS 사람수
FROM 테이블명
GROUP BY 성별

SELECT NAME, COUNT(*) AS COUNT
FROM ANIMAL_INS
WHERE NAME IS NOT NULL
GROUP BY NAME
HAVING COUNT(*) > 1
ORDER BY NAME 

ODER BY NAME은 ORDER BY NAME ASC랑 같은 말이고 NAME별로 오름차순 정렬
DESC는 내림차순 정렬


-- 코드를 입력하세요
SELECT NAME, COUNT(*) AS COUNT
FROM ANIMAL_INS
GROUP BY NAME
HAVING COUNT(*) > 1

SELECT NAME, COUNT(*) AS COUNT
FROM ANIMAL_INS
WHERE 1=1
GROUP BY NAME
HAVING COUNT(*) > 1

-- AS 는 생략가능
SELECT NAME, COUNT
FROM (
    SELECT NAME, COUNT(*) AS COUNT
    FROM ANIMAL_INS
    GROUP BY NAME
    ) AS A
WHERE COUNT > 1



-- 코드를 입력하세요
SELECT HOUR(DATETIME) AS HOUR,COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) >= 9
AND HOUR(DATETIME) < 20
GROUP BY HOUR(DATETIME)
ORDER BY HOUR(DATETIME)


-- 코드를 입력하세요
SELECT A.HOUR, CASE WHEN B.COUNT IS NULL THEN 0 ELSE B.COUNT END AS COUNT
FROM (
    SELECT 0 HOUR UNION ALL SELECT 1 HOUR UNION ALL SELECT 2 HOUR UNION ALL 
    SELECT 3 HOUR UNION ALL  SELECT 4 HOUR UNION ALL SELECT 5 HOUR UNION ALL 
    SELECT 6 HOUR UNION ALL  SELECT 7 HOUR UNION ALL SELECT 8 HOUR UNION ALL 
    SELECT 9 HOUR UNION ALL  SELECT 10 HOUR UNION ALL SELECT 11 HOUR UNION ALL 
    SELECT 12 HOUR UNION ALL  SELECT 13 HOUR UNION ALL SELECT 14 HOUR UNION ALL 
    SELECT 15 HOUR UNION ALL  SELECT 16 HOUR UNION ALL SELECT 17 HOUR UNION ALL 
    SELECT 18 HOUR UNION ALL  SELECT 19 HOUR UNION ALL SELECT 20 HOUR UNION ALL 
    SELECT 21 HOUR UNION ALL  SELECT 22 HOUR UNION ALL SELECT 23 HOUR
    ) A
LEFT JOIN (
    SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS 
    GROUP BY HOUR(DATETIME)
    ) B
ON A.HOUR = B.HOUR
"""



